### PR TITLE
Added our own dependencies

### PR DESCRIPTION
**Pull request by bwuphan**

### CODE REVIEW

**Comment by SherryH** [comment]
Wow we are getting ambitious using Bootstrap alpha! Can we remove the floobit files from the PR? The .floo and .flooignore don't need to be committed.

**Comment by bwuphan** [comment]
Whoops I just used what the recastly sprint had. I'll remove it

**Comment by SherryH** [comment]
Just add _.floo_ and _.flooignore_ to the _.gitignore_ file then those files will not get committed.

**Comment by bwuphan** [comment]
Do you see the changes now?

**Pull request merged**
